### ISSUE TITLE
Meta-Issue : Index Names & MatchingIndex

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-client#1374]
The idea of this issue is to regroup all the work we done / we have to do, in order to handle correctly the indexes on Cozy-Client. 

> We have two issues with indexes in Cozy-Client:
The first one is related to the usage of logical mango operators ($or, $and, $in, etc.) at the top level.Cozy-Client doesn't handle them properly and creates indexes named $or/$and/$etc
(see https://github.com/cozy/cozy-client/issues/1270). This can lead to conflicts with the indexes.
Even worse, when we create a partialFilter without declaring a top-level $and, like [{foo: bar, truc:muche}], the index name on the Cozy-Client side is correct (foo_truc). However, when we inspect the design doc, CouchDB automatically adds the $and, and it becomes $and: [{foo: bar}, {truc: muche}]
The second issue is the automatic deletion of what Cozy-Client considers "inconsistent" indexes. When Cozy-Client receives an event of type index_not_found or not_usable_index, it performs some leanup by querying all the indexes on the relevant doctype and checks if the index name matches the indexed fields in the design doc. Due to CouchDB's automatic addition of a top-level logical operator with an implicit $and, Cozy-Client doesn't handle this well and considers the index as "inconsistent," leading to its deletion.
The real solution is to make Cozy-Client capable of handling logical operators at the top level of indexes / partialFilters. To achieve this, we need to rename all the indexes. However, doing so would result in the deletion of indexes judged inconsistent by the current Cozy-Client version. Newer versions of Cozy-Client will create new, correct indexes, but older apps will delete them as they won't correspond to the previous logic. This process of create / delete / create / delete will become a nightmare.

From https://github.com/cozy/cozy-client/pull/1373 

Here is the actions we need to take: 

- [X] Remove the destroy of inconsistent index (https://github.com/cozy/cozy-client/pull/1373) 
- [ ] Generate the right name for the index, even if there is logical operator in selector and partialFilter
- [ ] Handle logical operator when creating an index (see issue https://github.com/cozy/cozy-client/issues/1270) 
- [ ] Convert implicit operator to explicit since CouchDB does that ([{foo: bar, truc:muche}] becomes $and: [{foo: bar}, {truc: muche}] in the design_doc). As a result, isMatchingIndex cannot function properly.

**Comment by paultranvan** [comment]
Solved by  https://github.com/cozy/cozy-client/pull/1495

**Comment by cballevre** [comment]
I don't think we've solved the problem of operators in selectors that was identified in this issue, but there is maybe an other issue on this subject ? 🤔
